### ISSUE TITLE
KDE Store archive needs to contain top level folder

### ISSUE THREAD

**Issue by FlyingFoX** [coxde/nordic-yakuake-skin#1]
The KDE Store archive has no top level folder. This prevents it from being directly installed from yakuake via the get new designs function.
Downloading the tar.gz and repacking it so that it contains a top level folder like `nordic-yakuake-skin` now makes it possible to open it from via the install design menu.

In the end it should look like

```
- nordic-yakuake-skin
  - tabs
  - title
  icon.png
  icon.svg
  tabs.skin
  title.skin
```

**Comment by coxde** [comment]
Thank you! Will fix soon.
